service: RestApi
frameworkVersion: "3"

provider:
  configValidationMode: off
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  getApiCalls:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      variable2: value2
      NODE_ENV: development
      KEY: secret123
      MONGO_DB_USER: srinivas6264
      MONGO_DB_PASSWORD: blKYbFdVyoNc2x1A
      MONGO_DB_HOST: mongodb+srv://srinivas6264:blKYbFdVyoNc2x1A@makersmind.kclzrvm.mongodb.net/RestApi
      MONGO_DB_DATABASE: RestApi