service: RestApi
frameworkVersion: "3"

provider:
  configValidationMode: off
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-1
  lambdaHashingVersion: 20201221
 

functions:
  getApiCalls:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      variable2: value2