service: RestApi
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-1
  lambdaHashingVersion: 20201221
 

functions:
  getApiCalls:
    handler: getApiCalls/index.handler
    events:
      - http:
          path: users/test
          method: GET
          cors: true
      - http:
          path: users/signup
          method: POST
          cors: true      