service: RestApi
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-1
  lambdaHashingVersion: 20201221
 

functions:
  getApiCalls:
    handler: index.handler
    events:
      - http: ANY /{proxy+}
      - http: ANY /