name: Node.js

on:
  pull_request:
    branches: [development]
  push:
    branches: [development]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16]

    steps:
      - uses: actions/checkout@v3
        with: { submodules: true }
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - if: matrix.node-version == 14
        run: npm install --global npm@7
      - run: npm ci
      - run: npm test
      - run: npm run test:dist

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: { node-version: 16 }
      - run: npm ci
      - run: npm run lint
